---
kafka_user: kafka
kafka_group: kafka

kafka_service_name: kafka
kafka_service_file: /usr/lib/systemd/system/{{ kafka_service_name }}.service
kafka_service_environment_file: /etc/sysconfig/{{ kafka_service_name }}
kafka_service_limit_no_file: 65536
kafka_service_limit_nproc: 65536
kafka_service_limit_mem_lock: infinity
kafka_service_timeout_stop_sec: 300

kafka_max_heap: 1G
kafka_min_heap: 1G

kafka_template_backup: yes
kafka_zookeeper_servers_ansible_group: zookeeper

kafka_broker_servers_ansible_group: broker
kafka_controller_servers_ansible_group: controller

kafka_log4j_dir: /var/log/kafka
kafka_log_dirs:
  - /var/data/kafka

kafka_server_properties_template: server.properties.j2
kafka_server_properties_file_name: server.properties

kafka_server_properties_file: "{{ kafka_home }}/config/{{ kafka_kraft_mode | ternary('kraft/', '') }}{{ kafka_server_properties_file_name }}"

kafka_skip_verify_listening: false
kafka_skip_verify_under_replicated: false

# Listeners
kafka_advertised_interface_name: eth1
kafka_advertised_host: "{{ ansible_facts[kafka_advertised_interface_name].ipv4.address }}"

kafka_listeners:
  - name: PLAINTEXT
    port: 9092
    tls: false

kafka_inter_broker_listener_name: PLAINTEXT
kafka_controller_listener_name: CONTROLLER
kafka_admin_listener_name: PLAINTEXT

kafka_jmx_enabled: false
kafka_jmx_management_port: 9990

kafka_admin:
  listener_name: PLAINTEXT

# Security
kafka_jaas_config_file_location: "{{ kafka_home }}/config/kafka-jaas.conf"

# GSSAPI
kafka_kerberos_keytab_file: files/{{ inventory_name }}/keytabs/{{ ansible_hostname }}/kafka.keytab
kafka_kerberos_keytab_location: "{{ kafka_home }}/security/ansible_kafka.keytab"

kafka_additional_conf: {}

kafka_jaas_debug: false

kafka_kraft_mode: "{{ kafka_kraft_mode | default(false) }}"
kafka_kraft_roles: "{{ group_names | intersect([kafka_broker_servers_ansible_group, kafka_controller_servers_ansible_group]) }}"

kafka_skip_setup_storage: true